apiVersion: hydra.ory.sh/v1alpha1
kind: OAuth2Client
metadata:
  name: my-new-oauth2-client
  namespace: default
spec:
  grantTypes:
    - client_credentials
    - implicit
    - authorization_code
    - refresh_token
  responseTypes:
    - id_token
    - code
    - token
  scope: "read write"
  secretName: test-client-custom2
  # these are optional
  redirectUris:
    - https://client/account
    - http://localhost:8080
  postLogoutRedirectUris:
    - https://client/logout
  audience:
    - audience-a
    - audience-b
  tokenEndpointAuthMethod: client_secret_basic