name: Install applications on Kubernets

on:
  push:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: "Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)"
        required: false
        default: false

jobs:
  install:
    strategy:
      matrix:
        KUBECTL_VERSION: ["v1.23.0", "v1.24.0", "v1.25.0", "v1.26.0", "v1.27.0"]
        include:
          - KUBECTL_VERSION: "v1.23.0"
            K3S_VERSION: "v1.23.17+k3s1"
          - KUBECTL_VERSION: "v1.24.0"
            K3S_VERSION: "v1.24.12+k3s1"
          - KUBECTL_VERSION: "v1.25.0"
            K3S_VERSION: "v1.25.8+k3s1"
          - KUBECTL_VERSION: "v1.26.0"
            K3S_VERSION: "v1.26.3+k3s1"
          - KUBECTL_VERSION: "v1.27.0"
            K3S_VERSION: "v1.27.1+k3s1"
    runs-on: self-hosted
    steps:
      - name: Cleanup
        continue-on-error: true
        run: |
          ls -la ./
          rm -rf ./* || true
          rm -rf ./.??* || true
          ls -la ./
          /usr/local/bin/k3s-uninstall.sh

      - uses: actions/checkout@v3

      - name: Install dependencies
        env:
          KUBECTL_VERSION: ${{ matrix.KUBECTL_VERSION }}
          HELM_VERSION: "v3.11.3"
          HELM_DIFF_VERSION: "3.6.0"
          HELMFILE_VERSION: "v0.152.0"
          YQ_VERSION: "v4.33.3"
        run: |
          ./.github/ci_config/bin/install-dependencies

      - name: Prepare the environment
        run: |
          DNAME='CN=CI,O=TheHyve,L=Utrecht,C=NL' ./bin/init
          yq -i -f process '.environments.default.values += ["../.github/ci_config/install-all.yaml", "../.github/ci_config/secrets.yaml.gotmpl"]' environments.yaml

      - name: Run helmfile template
        env:
          FIREBASE_ADMINSDK_JSON: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
        run: |
          helmfile template

      - name: Install K3S
        env:
          INSTALL_K3S_VERSION: ${{ matrix.K3S_VERSION }}
          INSTALL_K3S_SYMLINK: "skip"
          K3S_KUBECONFIG_MODE: "644"
        run: |
          curl -sfL https://get.k3s.io | sh -s - --disable traefik --disable-helm-controller
          cp /etc/rancher/k3s/k3s.yaml ~/.kube/config

      - name: Install RADAR-Kubernetes
        env:
          FIREBASE_ADMINSDK_JSON: ${{ secrets.FIREBASE_ADMINSDK_JSON }}
        run: |
          echo "kubeconfig: $KUBECONFIG"
          kubectl get pods --all-namespaces

          helmfile sync

      - name: Report cluster state
        if: always()
        run: |
          kubectl get pods --all-namespaces

      # Enable tmate debugging of manually-triggered workflows if the input option was provided
      - name: Manually triggered tmate session
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
        with:
          limit-access-to-actor: true

      - name: Slack Notification
        if: ${{ failure() }}
        uses: rtCamp/action-slack-notify@v2
        env:
          SLACK_CHANNEL: ci-notifications
          SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
          SLACK_ICON: https://github.com/rtCamp.png?size=48
          SLACK_MESSAGE: 'The job has failed, go to https://github.com/RADAR-base/RADAR-Kubernetes/actions and use SSH for more information'
          SLACK_TITLE: Post Title
          SLACK_USERNAME: rtCamp
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - name: Setup tmate session if jobs have failed
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
        timeout-minutes: 15
        with:
          limit-access-to-actor: true

      # Takes very long to upload artifcats for some reason
      # https://github.com/RADAR-base/RADAR-Kubernetes/actions/runs/5642728153/job/15283146473
      - name: Prepare the logs for upload
        if: ${{ failure() }}
        run: |
          sudo chmod -R 777 /var/log/pods

      - name: Upload logs as artifacts
        uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: kubenretes-logs-${{ matrix.K3S_VERSION }}
          path: /var/log/pods
          if-no-files-found: ignore
          
  check-gitignore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Check gitignore
        run: |
          echo "Checking whether any files that should be ignored are uploaded"
          echo
          if find . -not -path './.git/*' -type f | git check-ignore --stdin --no-index; then
            echo
            echo "Remove the above files from this branch"
            exit 1
          else
            echo "No ignored files have been added"
          fi
